name: build
on:
  push:
    branches:
      - main
    tags:
      - '!*' # Do not execute on tags
jobs:
  test:
    strategy:
      matrix:
        os:
          - { index: 1, os-name: 'ubuntu-latest', os-label: 'Linux' }
          - { index: 2, os-name: 'macos-latest', os-label: 'macOS' }
          - { index: 3, os-name: 'windows-latest', os-label: 'Windows' }
        node: [ '16', '20' ]
    name: "Tests (${{ matrix.os.os-label }}, node:${{ matrix.node }})"
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4

      - name: install dependencies
        run: make install

      - name: run linter
        run: make lint

      - name: run tests
        run: make test
  coverage:
    needs: [ test ]
    name: coverage
    if: ${{ github.event_name == 'push' }} # Publish coverage only for push commits, not PRs.
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install dependencies
        run: make install

      - name: publish code coverage to code-climate (duh)
        uses: paambaati/codeclimate-action@v6.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage